export const G = 70;
export const ONE = G + 75;
export const TWO = ONE + 75;
export const THREE = TWO + 75;
export const FOUR = THREE + 75;
export const FIVE = FOUR + 75;
export const SIX = FIVE + 75;
export const SEVEN = SIX + 75;
export const DEFAULT = 60;
